server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medicine
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ZhiYaoBaoGe

#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: false
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag
      logic-not-delete-value: 0
      logic-delete-value: 1
logging:
  level:
    root: info
    web: debug
